<a href="https://colab.research.google.com/github/dborges14/SamsungInovationCampus_AI/blob/main/Chapter3_NumPy_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy array operations**

In [3]:
import numpy as np

In [4]:
a = [1, 2, 3]
b = [4, 5, 6]
a + b       # For lists, '+' means concatenation.

[1, 2, 3, 4, 5, 6]

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b				# For NumPy arrays, '+' means element-wise addition

array([5, 7, 9])

In [ ]:
a = [1, 2, 3]
3 * a				# For lists, '*' means repetition.

In [8]:
b = np.array([1, 2, 3])
3 * b				# For NumPy arrays, '*' means multiplication of the elements.

array([3, 6, 9])

In [11]:
np.array(3 * [1, 2, 3])


array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [9]:
np.repeat(b, 3)			# Use repeat() function to repeat each element.

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [10]:
np.tile(b, 3)			# Use tile() function to repeat the sequence.

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])			
a + b	

array([5, 7, 9])

In [15]:
b-a

array([3, 3, 3])

In [16]:
a*b

array([ 4, 10, 18])

In [18]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

**Universal functions:**

In [21]:
x = np.array([0, 1, 2, 3])		
x**3

array([ 0,  1,  8, 27])

In [22]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [23]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [24]:
np.sin(x)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [19]:
type(np.sin)

numpy.ufunc

image.png