<a href="https://colab.research.google.com/github/dborges14/SamsungInovationCampus_AI/blob/main/Chapter3_NumPy_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy array basics**

In [ ]:
import numpy as np    # Import the NumPy package and abbreviate its name as 'np'. 
np.__version__        # Currently installed NumPy version.

'1.19.5'

In [ ]:
arr1 = np.array([1,3,5,7,9])		# Create an array from a list.
arr2 = np.array((1,3,5,7,9))		# Create an array from a tuple.
arr1

array([1, 3, 5, 7, 9])

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
arr3 = arr1					# Simple assignment.

In [ ]:
arr4 = arr1.copy()			# Make a shallow copy. 
print(id(arr1))
print(id(arr4))

140461720511952
140461789136576


In [ ]:
arr1 = np.array([111, 2.3,  True, False, False]) 		# Numeric and Boolean values entered.
arr1									# Automatic conversion to the float type.

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [ ]:
arr2 = np.array([111, 2.3, 'python', 'abc']) 			# Numeric and string values entered. 
arr2									# Automatic conversion to the string type.

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [ ]:
arr3 = np.array([111, True, 'abc']) 				# Numeric, Boolean and string values entered.
arr3									# Automatic conversion to the string type.

array(['111', 'True', 'abc'], dtype='<U21')

In [ ]:
np.arange(10)				  # Array corresponding to the range 0~9.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10,20)			# Array corresponding to the range 10~19.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(10, 20, 3)			# Array corresponding to the range10~19, step = 3.

In [ ]:
arr = np.arange(10) 	
len(arr) 		 						# Returns the length. Same as with Python list.

10

In [ ]:
arr.size                # Attribute 'size' equals the number of elements. 

10

In [ ]:
np.linspace(0, 10, 5)					# Equally spaced 5 numbers between 0 and 10.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.zeros(10)   # 10 zeros.

In [ ]:
np.zeros((3,4))				# The shape is given as a tuple.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros(5, dtype ='int64')			# Specified the data type of the elements.

array([0, 0, 0, 0, 0])

In [ ]:
zeros = np.zeros(5, dtype ='int64')
zeros.dtype

dtype('int64')

In [ ]:
arr = np.ones((2,3), dtype ='int_')		 # The shape given as a tuple. Data type is specified. 	
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.astype('float32')		 # Re-cast the data type as 'float32'.

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
a = np.array([1, 2, 3, 4, 5])		# A one dimensional NumPy array.
a[:2]

array([1, 2])

In [ ]:
a[-1]				# The first element from last.

5

In [ ]:
a[:]				# The whole array.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])	# This is a 3 x 3 two dimensional array (matrix).
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[1]				# The row 1.

array([4, 5, 6])

In [ ]:
a[-1]				# The last row.

In [ ]:
a[:]				# The whole array (matrix).

In [ ]:
a[:2]				# From the row 0 to the row 1 (excluding the row 2).

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[2][1]			# The element from the row 2 and the column 1.	

In [ ]:
a[2, 1]			# The same as above.

In [ ]:
a[[0, 2]]			# The rows 0 and 2.

In [ ]:
a[1:, 1:]			# From the row 1 to the end. From the column 1 to the end.

array([[5, 6],
       [8, 9]])

In [ ]:
arr = np.arange(100)		# A sequence from 0 to 99.

In [ ]:
arrMask = ((arr % 5) == 0) 		# A Boolean array. True if multiple of 5, else False.
arr[arrMask]			# Apply fancy indexing. 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
arrMask = ( ( (arr % 5) == 0 )  & ( arr >0) )	# A Boolean array. True if multiple of 5 or 0, else False. 
arr[arrMask]			# Apply fancy indexing.

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [ ]:
a.size				 # The total number of elements.

9

In [ ]:
a.shape				 # The shape: number of rows and columns.

(3, 3)

In [ ]:
a.ndim				 # The number of dimensions.

2

In [ ]:
a = np.arange(15)			 # A sequence from 0 to 14. A 1D array.
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a.reshape(3,5)			 # Reshape it as a 3 x 5 matrix (2D array). This is just a view.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a.shape = (3, 5)			# Change directly the 'shape' attribute. 
a				# The reshaping is now permanent

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a = np.array([2,5,1,3])			 # This is a 1D array (rank 1).
a.shape

(4,)

In [ ]:
a = a.reshape(4,1)			# After reshaping, 'a' is reassigned.
a        # Now, a single column matrix.

array([[2],
       [5],
       [1],
       [3]])

In [ ]:
a.shape			# The reshaping is permanent.

(4, 1)

In [ ]:
a = np.arange(10)			 # A sequence from 0 to 9. A 1D array (rank 1).
b = a.reshape(2,5)			 # Reshape as 2 x 5 then assign to 'b'.
a[0] = -999
b         # You can see that 'a' and 'b' share the same memory space!

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [ ]:
c = a.reshape(2,5).copy()		# Now, make a shallow copy.
c[0, 0] = 0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
a = np.array([1, 2, 3])		# A 1D array (rank 1).
b = np.append(a, [4, 5, 6])		# Append new values and create a new array object.
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1, 2], [3, 4]])        		# A 2D array.
b = np.append(a, [[9, 9]], axis=0)      	# Append a row and create a new array object.
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [ ]:
c = np.append(a, [[9], [9]] , axis=1)	    # Append a column and create a new array object.
c

array([[1, 2, 9],
       [3, 4, 9]])

In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)			 # Delete the element at position 0. Just a view.

array([2, 3, 4, 5, 6])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.delete(a, (0, 2, 4))		# Delete the elements at positions 0, 2 and 4. Just a view.

array([2, 4, 6])

In [ ]:
np.delete(a, 0, axis = 0)		# Delete the row 0. Just a view. 

In [ ]:
np.delete(a, 1, axis = 1)		# Delete the column 1. Just a view.

## Time for Coding Exercise **'ex_0201.ipynb'** 